### ISSUE TITLE
Blender 4.1 

### ISSUE THREAD

**Issue by luigipacheco** [Mahrkeenerh/SerpensExtendedScripting#1]
Doest seem to work on Blender  4.1 (Alpha)

**Comment by Mahrkeenerh** [comment]
Could you describe in more details what is not working? How to reproduce the issue?
Are you getting any console errors?
What serpens version are you on?

**Comment by luigipacheco** [comment]
I just unistalled and installed again the package in serpens, its showing the nodes again. before it was showing red undefined nodes. (no errors)  ill keep testing but it looks like its working just needed to reinstall.

**Comment by softyoda** [comment]
Do you install like conventional addon (download zip and press install in preferences) or does this require special installation method ?

(it doesn't work in conventional method and there is no installation procedure in readme.md)

**Comment by Mahrkeenerh** [comment]
thank you for further information on the issue
Solved in #2
